### ISSUE TITLE
Issue with "info" button within a file

### ISSUE THREAD

**Issue by CrazyTrain422** [idoodler/Fily_issues#1]
This is happening on my iPhone 6s running 10.3.3, Jailbroken using g0blin. When I am on Fily and click on a file or document, then within the file/document, the app crashes every time I try to press "info". Everything else works just as it is supposed to aside from this one issue.

**Comment by idoodler** [comment]
@CrazyTrain422 On what type of file or document does this happen? Is it just with one filetype? What version of Fily do you use?
